# Generated by Django 4.2.7 on 2023-12-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_alter_permission_managers_permission_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=10)),
                ('version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission')),
                ('sistema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sistemas.sistemas')),
            ],
            options={
                'verbose_name': 'Permisos Sistemas',
                'verbose_name_plural': 'Permisos Sistemas',
                'unique_together': {('sistema', 'permiso')},
            },
        ),
    ]
